# Generated by Django 4.0.3 on 2022-04-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_data', models.CharField(max_length=10000)),
                ('post_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.BigIntegerField()),
                ('media_type', models.CharField(max_length=50)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
