# Generated by Django 4.0.3 on 2022-04-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instadata',
            unique_together={('media_id', 'comments')},
        ),
    ]
