# Generated by Django 4.0.3 on 2022-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_alter_facebookposts_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.BigIntegerField()),
                ('media_type', models.CharField(max_length=50)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
