# Generated by Django 4.0.3 on 2022-03-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_instadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstaData',
            new_name='IgData',
        ),
    ]
