# Generated by Django 4.0.3 on 2022-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeetings',
            name='object_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
